services:
  backend:
    build: ./
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
    depends_on:
      - db
    networks:
      - app-network
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "start:prod"]

  frontend:
    build: ../../sboard_test_task  
    ports:
      - "5173:5173"   
    environment:
      VITE_API_URL: http://localhost:3000
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb  
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge